# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Ben Hertzberg
tagline:          'A Jekyll theme'
description:      'Hallo'
url:              http://benhertzberg.github.io
baseurl:          /testwebsite

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
